### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by Draxent** [aissat/easy_localization#172]
I am experiencing a strange cache issue with the gender
I have the following code:

```
  Widget _buildText(String gender) {
    final noItemsStr = LangKeys.noItemsViewer_noItems;
    print('$noItemsStr $gender');
    return Text(
        noItemsStr.tr(args: [], gender: gender),
      );
  }
```
The print is printing the following text

`framework.noItemsViewer.noItems femminile`

But when I run the app, I get the following error

`Missing message : Not found this Key ["framework.noItemsViewer.noItems.female"]`

But I have no word 'female' anywhere in my code.
I guess the issue is that before the gender was named 'female', then I rename it to 'femminile', and now they change is not there.
I tried to wipe the data of my simulator, or install a new simulator, but I experience this issue everywhere.

Could you help me understand why? Could it be a bug in the code?

**Comment by aissat** [comment]
@Draxent plz full example with translate files

**Comment by Draxent** [comment]
But I removed the arguments from the code **_buildText** to reduce complexity.

**it.yaml**

```
framework:
  noItemsViewer:
    noItems:
      maschile: 'Non hai nessun {} memorizzata{}'
      femminile: 'Non hai nessuna {} memorizzata{}'
```

**en.yaml**

```
framework:
  noItemsViewer:
    noItems: 'You have no {} stored{}'
    noItemsDisabled: 'You have no {} disabled{}'
```
