### ISSUE TITLE
The method 'ensureInitialized' isn't defined for the type 'EasyLocalization'

### ISSUE THREAD

**Issue by yoyomaster73** [aissat/easy_localization#324]
Thanks you for your package!
I have a problem when I do that:
```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:easy_localization/easy_localization.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]).then((_) {
    runApp(EasyLocalization(
      child: MyApplication(),
      useOnlyLangCode: true,
      startLocale: Locale('fr'),
      fallbackLocale: Locale('fr'),
      supportedLocales: [
        Locale('fr'),
        Locale('en'),
      ],
      path: 'assets/translations',
    ));
  });
}

```

VS Code give me this error:
```

The method 'ensureInitialized' isn't defined for the type 'EasyLocalization'.
Try correcting the name to the name of an existing method, or defining a method named 'ensureInitialized'.dart(undefined_method)

```

I use "flutter channel stable" and:
```

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  flutter_icons: ^1.1.0
  easy_localization: ^2.3.3+1

  cupertino_icons: ^1.0.0

dev_dependencies:
  #flutter_test:
    #sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  path: ^1.8.0-nullsafety.1
  
```
