### ISSUE TITLE
parsed_path.dart:1:1: Error: The specified language version is too high

### ISSUE THREAD

**Issue by yoyomaster73** [aissat/easy_localization#325]
I try to follow the README but I can't make this package work.
I had several errors (I opened another issue and I commented a closed issue).
When I try to execute the translation I have this error:
```

$ flutter pub run easy_localization:generate
Unable to spawn isolate: /home/user/.pub-cache/hosted/pub.dartlang.org/path-1.8.0-nullsafety.3/lib/path.dart:1:1: Error: The specified language version is too high. The highest supported language version is 2.10.

```

I use "flutter channel stable" and:

```

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
  flutter_icons: ^1.1.0
  easy_localization: ^2.3.3+1

  cupertino_icons: ^1.0.0

dev_dependencies:
  #flutter_test:
    #sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  path: ^1.8.0-nullsafety.1
  
```

I tried several times to modify "intl" "nullsafety" version and make after:
```

rm -Rf /home/user/.pub-cache
cd project/
rm -f pubspec.lock
flutter pub run easy_localization:generate

```

Each time I have this error.
