### ISSUE TITLE
Invalid description in the "easy_localization" pubspec on the "easy_logger" dependency

### ISSUE THREAD

**Issue by naamapps** [aissat/easy_localization#339]
I'm getting this error:
```
Invalid description in the "easy_localization" pubspec on the "easy_logger" dependency: "packages/easy_logger" is a relative path, but this isn't a local pubspec.
   ╷
20 │     path: packages/easy_logger
   │           ^^^^^^^^^^^^^^^^^^^^
   ╵
pub finished with exit code 65
exit code 65
```

In my pubspec I get the develop branch because I can't use the latest 3.0 null safety version in pub.dev (I'm on flutter 1.22.6).
```
  easy_localization:
    git:
      url: git://github.com/aissat/easy_localization.git
      ref: develop
```

Please help,
Thanks
