### ISSUE TITLE
Problem with 'auto_route', 'build_runner' and 'flutter_gen' packages

### ISSUE THREAD

**Issue by jbt-cii** [aissat/easy_localization#344]
I work with MacBook Pro (with the latest M1 chip) and flutter "channel stable":

```
✗ flutter doctor -v
[✓] Flutter (Channel master, 1.27.0-5.0.pre.18, on macOS 11.2.1 20D74 darwin-arm, locale fr-FR)
    • Flutter version 1.27.0-5.0.pre.18 at /opt/homebrew/Caskroom/flutter/1.22.6/flutter
    • Framework revision 50897c98fc (8 days ago), 2021-02-16 20:13:53 -0800
    • Engine revision 9bcb3bfb0e
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/myhome/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile)  • emulator-5554                        • android-arm64  • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • D224D539-B086-4830-8904-39D18F34B3E5 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 88.0.4324.192

• No issues found!

```

In the "build_runner" package GIT issues I talked about a compatibility problem when I use "auto_route" package which requires the usage of these packages: "build_runner" and "flutter_gen".

I use these dependencies in 'pubspec.yaml' file:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
...
  auto_route: ^0.6.9
 ...
  easy_localization:  ^3.0.0
  easy_localization_loader:  ^0.0.2
...
  # flutter_gen: ^1.3.1
  # flutter_gen: ^2.0.0
...

dev_dependencies:
#flutter_test:
#sdk: flutter
  #build_runner:
  build_runner: ^1.11.1
  auto_route_generator: ^0.6.10

...

```

When I enable "flutter_gen" (1.3.1 or 2.0.0) I get:

```
Because no versions of easy_localization_loader match >0.0.2 <0.1.0 and easy_localization_loader 0.0.2 depends on xml ^3.5.0, easy_localization_loader ^0.0.2 requires xml ^3.5.0.
And because flutter_gen >=0.0.6 <2.0.0 depends on xml ^4.2.0, easy_localization_loader ^0.0.2 is incompatible with flutter_gen >=0.0.6 <2.0.0.
So, because myproject depends on both flutter_gen ^1.3.1 and easy_localization_loader ^0.0.2, version solving failed.
Running "flutter pub get" in myproject...             
pub get failed (1; So, because myproject depends on both flutter_gen ^1.3.1 and easy_localization_loader ^0.0.2, version solving
failed.)

```

[Issue declared in 'build_runner' GIT](https://github.com/dart-lang/build/issues/2835#issuecomment-785230104)
