### ISSUE TITLE
resetLocale sets the locale with country code

### ISSUE THREAD

**Issue by jezsung** [aissat/easy_localization#376]
I have translations at `assets/translations/` with two locales `en.json` and `ko.json`  and the below is my code.

``` dart
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();
  runApp(
    EasyLocalization(
      supportedLocales: const [
        Locale('en'),
        Locale('ko'),
      ],
      fallbackLocale: const Locale('en'),
      path: 'assets/translations',
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('home.title'.tr()),
      ),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () {
                if (Localizations.localeOf(context) == const Locale('en')) {
                  context.setLocale(const Locale('ko'));
                } else {
                  context.setLocale(const Locale('en'));
                }
              },
              child: Text('Toggle Locale'),
            ),
            ElevatedButton(
              onPressed: () {
                context.resetLocale();
              },
              child: Text('Reset Locale'),
            )
          ],
        ),
      ),
    );
  }
}
```

Whenever I clicked on the `Reset Locale` button, it throws the error `Unable to load asset: assets/translations/ko-US.json`. It seems it occurred because of the missing the `ko-US.json` file. But shouldn't it load the available locale when there's a matched file with language code?

``` yaml
name: easy_localization_test
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

```
