### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by duck-dev-go** [aissat/easy_localization#425]
On IOS when I change the device language of the device multiple time I get the following error

![image](https://user-images.githubusercontent.com/15832303/131205430-ac951b6c-0c9a-4495-8a20-2e979da47715.png)

The whole app doesn't work and I even need to uninstall to get it working again. It doesn't matter which language I switch to. Usually it happens after 3 to 6 times switching language. 

I wrap my app widget with the EasyLocalization

  ```
runApp(
    EasyLocalization(
      supportedLocales: [
        Locale('af'),
        Locale('da'),
        Locale('de'),
        Locale('el'),
        Locale('en'),
        Locale('es'),
        Locale('fi'),
        Locale('fr'),
        Locale('hu'),
        Locale('id'),
        Locale('it'),
        Locale('ms'),
        Locale('nb'),
        Locale('nl'),
        Locale('pl'),
        Locale('pt'),
        Locale('ru'),
        Locale('sv'),
        Locale('tr'),
      ],
      path: 'assets/translations',
      useOnlyLangCode: true,
      fallbackLocale: Locale('en'),
      child: _App( ),
    ),
  );
```

And I have all my json files in assets/translations. I import the translations like this

```
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/translations/notifications/
```
