### ISSUE TITLE
Update pub dev

### ISSUE THREAD

**Issue by And96** [aissat/easy_localization#637]
Starting to have problems with packages not updated.
Please upgrade to lastest version to solve incompatibility

```
Because easy_localization >=3.0.2-dev.6 depends on intl >=0.17.0-nullsafety <=0.18.1 and every version of package from git depends on intl ^0.19.0,
  easy_localization >=3.0.2-dev.6 is incompatible with package from git.
So, because depends on both package from git and easy_localization >=3.0.3, version solving failed.

```
Please update packages. Specifically intl 

**Latest version is: 0.19.0** 
https://pub.dev/packages/intl

**Comment by tajjacob** [comment]
I already create a pull request on update intl.
In the meantime, you can use this branch:
```

  easy_localization:
    git:
      url: https://github.com/tajjacob/easy_localization.git
      ref: upstream/2023-52-update-intl
```
